In [1]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-1.62061904, -1.03123202,  1.10529999],
       [-0.81738871, -0.04445177,  0.91512524]])

In [2]:
data * 10

array([[-16.20619043, -10.31232018,  11.05299986],
       [ -8.17388714,  -0.44451775,   9.15125236]])

In [3]:
data + data

array([[-3.24123809, -2.06246404,  2.21059997],
       [-1.63477743, -0.08890355,  1.83025047]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
data1 = [6,7,5,8,0,1]
arr1 = np.array(data1)
arr1

array([6, 7, 5, 8, 0, 1])

In [8]:
data2 = [[1,2,3,4,], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2,3,2))

array([[[-1.28822975e-231,  3.11107877e+231],
        [ 3.95252517e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [23]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.0, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [30]:
arr = np.array([[1.,2.,3.,], [4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr ** arr

array([[1.0000e+00, 4.0000e+00, 2.7000e+01],
       [2.5600e+02, 3.1250e+03, 4.6656e+04]])

In [33]:
arr ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr_slice = arr[5:8]
arr_slice[0] = 15
arr


array([ 0,  1,  2,  3,  4, 15,  6,  7,  8,  9])

In [43]:
arr_copy = arr[5:8].copy()
arr_copy[0]= 15
arr

array([ 0,  1,  2,  3,  4, 15,  6,  7,  8,  9])

In [44]:
arr is arr_slice

False

In [45]:
arr is arr_copy

False

In [51]:
a = [3]

In [52]:
b = a

In [53]:
a is b

True

In [54]:
c = a.copy()

In [55]:
a is c

False

In [57]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2d[2]

array([7, 8, 9])

In [59]:
arr2d[0][2]

3

In [61]:
arr3d = np.array([[[1,2,3], [4,5,6,]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [13]:
points = np.arange(-5, 5, 0.01)
points.shape

(1000,)

In [14]:
xs, ys = np.meshgrid(points.points)
ys

AttributeError: 'numpy.ndarray' object has no attribute 'points'

In [15]:
arr = np.random.randn(4,4)
arr

array([[ 0.93593557,  0.19485006,  0.3263949 , -0.30618238],
       [ 0.37894846,  0.79605629, -0.15283133, -0.26442644],
       [-0.20292395,  0.07647041, -0.32490601,  0.07917637],
       [-0.01222203, -0.20227959,  0.70200986, -1.25699657]])

In [16]:
np.where(arr>0.2, 2, -2)

array([[ 2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [-2, -2, -2, -2],
       [-2, -2,  2, -2]])

In [18]:
arr = np.random.randn(5,4)
arr

array([[-1.52772999, -0.28475833,  0.86722991,  0.41847033],
       [-0.04204349,  0.03943411, -0.71835237, -0.57606942],
       [ 0.45077525,  3.12206005, -0.23068998,  0.9894758 ],
       [-0.40253585, -0.21759469, -0.50255508, -0.33969652],
       [-1.50748456,  0.05382246,  0.8868069 ,  1.36895789]])

In [19]:
arr.mean()

0.0923761206655997

In [20]:
np.mean(arr)

0.0923761206655997

In [21]:
arr.sum()

1.847522413311994

In [22]:
arr.mean(axis = 1)

array([-0.13169702, -0.32425779,  1.08290528, -0.36559554,  0.20052567])

In [23]:
arr.sum(axis = 0)

array([-3.02901864,  2.71296359,  0.30243938,  1.86113808])

In [25]:
arr = np.array([0,1,2,3,4,5,6,7])
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [27]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0])