In [6]:
import pandas as pd
import numpy as np

data = pd.Series(np.random.randn(9), index=[['a','a','a','b','b','c','c','d','d'],
                                            [1,2,3,1,3,1,2,2,3]])

data

a  1   -0.408238
   2    1.034358
   3    0.571570
b  1   -0.515735
   3   -1.120277
c  1   -0.024497
   2    0.958225
d  2    0.199934
   3   -0.943931
dtype: float64

In [7]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [8]:
data['b']

1   -0.515735
3   -1.120277
dtype: float64

In [9]:
data['b':'c']

b  1   -0.515735
   3   -1.120277
c  1   -0.024497
   2    0.958225
dtype: float64

In [10]:
data.loc[['b', 'd']]

b  1   -0.515735
   3   -1.120277
d  2    0.199934
   3   -0.943931
dtype: float64

In [12]:
data.loc[:, 2]

a    1.034358
c    0.958225
d    0.199934
dtype: float64

In [13]:
data.unstack()

1         2         3
a -0.408238  1.034358  0.571570
b -0.515735       NaN -1.120277
c -0.024497  0.958225       NaN
d       NaN  0.199934 -0.943931

In [14]:
data.unstack().stack()

a  1   -0.408238
   2    1.034358
   3    0.571570
b  1   -0.515735
   3   -1.120277
c  1   -0.024497
   2    0.958225
d  2    0.199934
   3   -0.943931
dtype: float64

In [15]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                    index=[['a','a','b','b'], [1,2,1,2]],
                    columns=[['ohio','ohio','colorado'],
                             ['green', 'red', 'greed']])
frame

ohio     colorado
    green red    greed
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [16]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      ohio     colorado
color     green red    greed
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [17]:
frame.swaplevel('key1','key2')

state      ohio     colorado
color     green red    greed
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [18]:
frame.sort_index(level=1)

state      ohio     colorado
color     green red    greed
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [19]:
frame.sort_index(level=0)

state      ohio     colorado
color     green red    greed
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [20]:
frame.sum(level='key2')

state  ohio     colorado
color green red    greed
key2                    
1         6   8       10
2        12  14       16

In [21]:
frame.sum(level='color', axis=1)

color      green  red  greed
key1 key2                   
a    1         0    1      2
     2         3    4      5
b    1         6    7      8
     2         9   10     11

In [22]:
frame = pd.DataFrame({'a': range(7), 'b':range(7,0,-1), 'c':['one', 'one','one',
                                                             'two','two','two','two',],
                     'd': [0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [23]:
frame2 = frame.set_index(['c', 'd'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [24]:
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [25]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [26]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','a','b'],
                    'data1': range(7)})

In [27]:
df2 = pd.DataFrame({'key': ['a', 'b', 'c'],
                    'data2': range(3)})

In [31]:
df3 = pd.DataFrame({'lkey': ['b','b','a','c','a','a','b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey':['a','b','d'],
                    'data': range(3)})

df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [32]:
df4

rkey  data
0    a     0
1    b     1
2    d     2

In [33]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data
0    b      0    b     1
1    b      1    b     1
2    b      6    b     1
3    a      2    a     0
4    a      4    a     0
5    a      5    a     0

In [29]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0
6   c      3      2

In [34]:
left1 = pd.DataFrame({'key': ['a','b','a','a','b','c'],
                       'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index = ['a', 'b'])

In [35]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [36]:
right1

group_val
a        3.5
b        7.0

In [37]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [38]:
pd.merge(left1, right1, left_on = 'key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [39]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [41]:
s1 = pd.Series([0,1],index=['a','b'])
s2 = pd.Series([2,3,4] ,index=['c','d', 'e'])
s3 = pd.Series([5,6] ,index=['f','g'])

In [42]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [44]:
pd.concat([s1,s2,s3], axis=1, sort=False)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [45]:
s4 = pd.concat([s1, s3])

In [46]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [48]:
pd.concat([s1,s4], axis=1, sort=False)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [49]:
pd.concat([s1,s4], join='inner')

a    0
b    1
a    0
b    1
f    5
g    6
dtype: int64

In [50]:
pd.concat([s1,s4], axis=1, join_axes=[['a','c','b','e']])

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [51]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [52]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [54]:
pd.concat([s1,s2,s3], axis=1, keys=['one', 'two', 'three'], sort=False)

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [56]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e','d','c','b','a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
              index=['f', 'e','d','c','b','a'])
a
            

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [57]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [58]:
b[-1] = np.nan

In [59]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [60]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [70]:
data = pd.DataFrame(np.arange(6).reshape((2,3)),
                    index=pd.Index(['ohio', 'colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'],
                    name='number'))
data

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [71]:
result = data.stack()
result

state     number
ohio      one       0
          two       1
          three     2
colorado  one       3
          two       4
          three     5
dtype: int64

In [72]:
result.unstack()

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [73]:
result.unstack(0)

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [74]:
result.unstack('state')

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [67]:
s1 = pd.Series([0,1,2,3], index=['a','b','c','d'])
s2 = pd.Series([4,5,6], index=['c','d','e'])
data2 = pd.concat([s1,s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [75]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [76]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [78]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64